version: '3'

services:
  app:
    image: docker_next
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./redux:/app/redux
      - ./services:/app/services
      - ./constants:/app/constants
      - ./components:/app/components
      - ./styles:/app/styles

      